# Generated by Django 5.1.1 on 2024-10-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comercio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("restaurante", "Restaurante"),
                            ("ferreteria", "Ferretería"),
                            ("heladeria", "Heladería"),
                            ("mascotas", "Tienda de Mascotas"),
                        ],
                        max_length=50,
                    ),
                ),
                ("direccion", models.CharField(max_length=150)),
                ("contacto", models.CharField(max_length=50)),
                ("redes_sociales", models.URLField(blank=True, null=True)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="fotos_comercios/"
                    ),
                ),
            ],
        ),
    ]
