# Generated by Django 5.1.2 on 2024-10-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercios", "0002_novedad"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comercio",
            name="contacto",
        ),
        migrations.RemoveField(
            model_name="comercio",
            name="direccion",
        ),
        migrations.RemoveField(
            model_name="comercio",
            name="redes_sociales",
        ),
        migrations.AddField(
            model_name="comercio",
            name="novedad",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comercio",
            name="categoria",
            field=models.CharField(max_length=50),
        ),
    ]
